version: "3.8"

services:
  app_new:
    container_name: calculator-app-new
    image: web-calculator:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      SENDGRID_KEY: ${SENDGRID_KEY}
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
      BIFROST_ACCOUNT_PROFILE_API: ${BIFROST_ACCOUNT_PROFILE_API}
      ODIN_SECRET: ${ODIN_SECRET}
      ODIN_HOST: ${ODIN_HOST}
    volumes:
      - "/c/Users/Enfec Solutions/Downloads/dockerdata:/usr/src/app/dockerdata"
